openapi: 3.0.3
info:
  title: DeadCrumbs API
  description: This is the API for for the DeadCrumbs application.
  version: '1'

paths:
  /Users:
    get:
      summary: returns all user as a list
      operationId: getUsers
      responses:
        200:
          description: Succesfull request! Returns a JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        404:
          description: No users found
  
  /User/{username}:
    get:
      summary: return the user
      operationId: getUser
      parameters: 
        - $ref: '#/components/parameters/username'
      responses:
        200:
          description: Succesfull request! Returns a user represented as JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: No user found called "username"
          
          
  /User:
    post:
      summary: adds a new user
      operationId: postUser
      requestBody:
        $ref: '#/components/requestBodies/user'
      responses:
        201:
          description: Succesfull request! Created new user
        400:
          description: Bad request! User not added

  /Location/{username}:
    get:
      summary: returns the location associated with username
      operationId: getLocation
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        200:
          description: Succesfull request! Returns a location represented as JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
                        
        404:
          description: No locations found!
                
  
  /Location:
    post:
      summary: adds a new location
      operationId: postLocation
      requestBody:
        $ref: '#/components/requestBodies/location'
      responses:
        201:
          description: Succesfull request! Created new location
        400:
          description: Bad request! Location not added
      
  
  /RSSI/{mac1}/{mac2}/{rssiDist}/{timeStamp}:
    post:
      summary: updates locations based on bluetooth sync
      operationId: postBluetoothSync
      parameters:
        - $ref: '#/components/parameters/mac1'
        - $ref: '#/components/parameters/mac2'
        - $ref: '#/components/parameters/rssiDist'
        - $ref: '#/components/parameters/timeStamp'
      responses:
        200:
          description: Succesfull request! Returns a user represented as JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: No user found called "username"
  
components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
          example: "jacob6565"
        mac_address:
          type: string
          format: "D6:11:A1:23"
      required: 
        - username
        - mac_address
        
    location:
      type: object
      properties:
        user_ref:
          type: string
        yaw:
          type: number
          format: double
        position:
          $ref: '#/components/schemas/position'
        timestamp:
          type: string
      required: 
        - user_ref
        - yaw
        - position
        - timestamp
        
    position:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: number
            format: double
            
  parameters:
    mac1:
      name: mac1
      in: path
      required: true
      description: The mac address of a user1.
      schema:
        type: string
        
    mac2:
      name: mac2
      in: path
      required: true
      description: The mac address of a user2.
      schema:
        type: string
    
    rssiDist:
      name: rssiDist
      in: path
      required: true
      description: distance estimated from RSSI
      schema:
        type: number
        format: double
    
    username:
      name: username
      in: path
      required: true
      description: The username of the user.
      schema:
        type: string
        
    timeStamp:
      name: timeStamp
      in: path
      required: true
      description: The time.
      schema:
        type: string

  requestBodies:
    location:
      description: a JSON object of a location
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/location'
            
    user:
      description: a JSON object of a user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'
    
