openapi: 3.0.3
info:
  title: Walking Skeleton API
  description: This is the API for the Walking Skeleton.
  version: '1'
  

servers:
  - url: url1
    description: production server
  - url: url2
    description: testing server
    

paths:
  /Locations:
    get:
      summary: returns all locations as a list
      operationId: getLocations
      responses:
        200:
          description: a JSON array of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
                
        404:
          description: no locations are in the database
          
  /Location/{deviceId}:
    get:
      summary: returns the location associated with device ID
      operationId: getLocation
      parameters:
        - $ref: '#/components/parameters/deviceId'
      responses:
        200:
          description: a json object of a location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
                
        400:
          description: retrival of location went wrong
        
        404:
          description: no device with that id
                
    delete:
      summary: deletes a location
      operationId: deleteLocation
      parameters:
        - $ref: '#/components/parameters/deviceId'
      responses:
       200:
        description: location deleted successfully
       400:
        description: deletion of location went wrong
       404:
        description: no location associated with devive ID
  
  /Location:
    post:
      summary: adds a new location
      operationId: postLocation
      requestBody:
        $ref: '#/components/requestBodies/Location'
      responses:
        200:
          description: location added successfully
        400:
          description: location added unsuccessfully

      

components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
        deviceId:
          type: integer
          format: int64
        locationValue:
          type: string
          example: some RSSI value
          
      required: 
        - id
        - deviceId
        - locationValue
      
  parameters:
    deviceId:
      name: deviceId
      in: path
      required: true
      description: The ID of the device.
      schema:
        type: integer
        format: int64
        minimum: 1
        
  requestBodies:
    Location:
      description: a json object of a location
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Location'
    
