openapi: 3.0.3
info:
  title: DeadCrumbs API
  description: This is the API for for the DeadCrumbs application.
  version: '1'

paths:
  /Users:
    get:
      summary: returns all user as a list
      operationId: getUsers
      responses:
        200:
          description: a JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'

  /User/{username}:
    get:
      summary: return the user
      operationId: getUser
      parameters: 
        - $ref: '#/components/parameters/username'
      responses:
        200:
          description: a user represented as json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /Location/{username}:
    get:
      summary: returns the location associated with username
      operationId: getLocation
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        200:
          description: a JSON object of a location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
                
        400:
          description: retrival of location went wrong
        
        404:
          description: no device with that id
                
  
  /Location:
    post:
      summary: adds a new location
      operationId: postLocation
      requestBody:
        $ref: '#/components/requestBodies/location'
      responses:
        201:
          description: location added successfully
        400:
          description: location added unsuccessfully

      

components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
          example: "jacob6565"
        mac_address:
          type: string
          format: "D6:11:A1:23"
      required: 
        - username
        - mac_address
        
    location:
      type: object
      properties:
        user_ref:
          type: string
        yaw:
          type: number
          format: float
        position:
          $ref: '#/components/schemas/position'
        timestamp:
          type: string
          format: date-time
      required: 
        - user_ref
        - yaw
        - position
        - timestamp
        
    position:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: number
            format: float
            
  parameters:
    username:
      name: username
      in: path
      required: true
      description: The username of the user.
      schema:
        type: string

  requestBodies:
    location:
      description: a JSON object of a location
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/location'
