version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: cd DeadCrumbs && chmod +x ./gradlew
      - run:
          command: cd DeadCrumbs && ./gradlew build -x test
      - run:
          name: Run Tests
          command: cd DeadCrumbs && ./gradlew test
