version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./MyApplication/gradlew
      - run:
          command: ./MyApplication/gradlew build
      - run:
          name: List Tasks
          command: ./MyApplication/gradlew tasks --all
