version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "/MyApplication/build.gradle" }}-{{ checksum  "/MyApplication/app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./MyApplication/gradlew
#      - run:
#          name: Download Dependencies
#          command: ./MyApplication/gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "/MyApplication/build.gradle" }}-{{ checksum  "/MyApplication/app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./MyApplication/gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: /MyApplication/app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /MyApplication/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
