version: 2.1

orbs:
 android: circleci/android@0.2.0
 windows: circleci/windows@2.2.0


jobs:
  build_APP:
    executor: android/android
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: cd DeadCrumbs && chmod +x ./gradlew
      - run:
          command: cd DeadCrumbs && ./gradlew build -x test
      - run:
          name: Run Tests
          command: cd DeadCrumbs && ./gradlew test
  build_API:
    description: Build API with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build API"
          command: cd aspnet-server-1/ && build.bat && dotnet run -p src/IO.Swagger/IO.Swagger.csproj --launch-profile web

workflows:
  build_API_and_APP:
    jobs:
      - build_API:
      - build_APP:
          requires:
            - build_API