version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./App/gradlew
      - run:
          command: ./App/gradlew build
      - run:
          name: Run Tests
          command: ./App/gradlew test
