version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: cd App && chmod +x gradlew
      - run:
          name: List dir
          command: ls
      - run:
          command: cd App && pwd && ls && gradlew build
      - run:
          name: Run Tests
          command: cd App && gradlew test
