/**
 * Walking Skeleton API
 * This is the API for the Walking Skeleton.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param deviceId 
 * @param locationValue 
 */
data class Location (
    val id: kotlin.Int,
    val deviceId: kotlin.Int,
    val locationValue: kotlin.String

) {
}