/**
 * DeadCrumbs API
 * This is the API for for the DeadCrumbs application.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param username 
 * @param mac_address
 */
data class User (
    val username: kotlin.String,
    val mac_address: kotlin.String

) {
}